select A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    sum(BS.SALES*B.PRICE) as TOTAL_SALES
from BOOK B
join AUTHOR A on A.AUTHOR_ID=B.AUTHOR_ID
join BOOK_SALES BS on BS.BOOK_ID=B.BOOK_ID
where SALES_DATE >= "2022-01-01" and SALES_DATE<"2022-02-01"
group by A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
order by AUTHOR_ID asc, CATEGORY desc;
